export * from './info/info.page';
export * from './info/details/details.comp';
export * from './info/version/version.comp';
export * from './fi-onboarding/fi-onboarding.page';
export * from './config-parameters/config-parameters.page';
export * from './prod-user-administration/prod-user-administration.page'
export * from './ica-maintenance/ica-maintenance.page';
export * from './mastercard-fee-rate-maintenance/mastercard-fee-rate-maintenance.page';
export * from './service-instance/service-instance.component';
export * from './rtp-transaction-activity/rtp-transaction-activity.page';
export * from './service-activity/service-activity.page';
export * from './status-report/status-report.page';
export * from './transaction-activity/transaction-activity.page';
export * from './process-view-error/process-view-error.page';